MAX_POSITION_COUNT :: 100;

struct Coordinates
{
   Count     : int;
   Positions : [MAX_POSITION_COUNT] vec2;
};

global C : Coordinates;

sub Foo :: {
    C.Count = 1;
    C.Positions[0] = {16.0, -21.0};
}

sub Bar : (A : int) : {
   "%d".(12 + 10 * A);
}

sub Baz :: word
{
   return (0x00112233_44556677_8899AABB_CCDDEEFF);
}

sub Bat : (A : int, Fn : (B : int) :) : {
    Fn (A);
}

program Main : (Arguments : []string) : int
{
~~
   Result := 100;
   if (Result = 0) break;

   if Result >= 60
   {
      "This is true.";
   }

   if Result = 99
   {
      "This is false.";
   }

   Bat (32, Bar);

   Bat (33, (X : int) : {
      "%d".(X);
   });

   return (Result);
}
